#!/bin/bash
#
# usage: ./tscript [test ...]
#
tests="a b c d e f g h i j k l m n o"
if [[ "$#" != "0" ]]; then
    tests="$*"
fi
for t in $tests; do
    case "$t" in
     a) echo "Starting test a"
        echo "Tests that it detects illegal file name, prints a stderr error message, and halts the program"
        echo "===== ./wordfreq JoeSventekIllegalFileName"
        ./wordfreq JoeSventekIllegalFileName
        echo "===== Stopping test a"
        ;;
     b) echo "Starting test b"
        echo "Tests that it detects illegal flags, prints a stderr error message, and halts the program"
        echo "===== ./wordfreq -x"
        ./wordfreq -x
        echo "===== Stopping test b"
        ;;
     c) echo "Starting test c"
        echo "Tests that it detects -i without -f or -a, prints a stderr error message, and halts the program"
        echo "===== ./wordfreq -i"
        ./wordfreq -i
        echo "===== Stopping test c"
        ;;
     d) echo "Starting test d"
        echo "Tests that it detects -af, prints a stderr error message, and halts the program"
        echo "===== ./wordfreq -af"
        ./wordfreq -af
        echo "===== Stopping test d"
        ;;
     e) echo "Starting test e"
        echo "Tests that it works correctly with no flags and no file names"
        echo "===== ./wordfreq"
        ./wordfreq <input | diff - teste.out | head
        echo "===== Stopping test e"
        ;;
     f) echo "Starting test f"
        echo "Tests that it works correctly with -l and no file names"
        echo "===== ./wordfreq -l"
        ./wordfreq -l <input | diff - testf.out | head
        echo "===== Stopping test f"
        ;;
     g) echo "Starting test g"
        echo "Tests that it works correctly with -p and no file names"
        echo "===== ./wordfreq -p"
        ./wordfreq -p <input | diff - testg.out | head
        echo "===== Stopping test g"
        ;;
     h) echo "Starting test h"
        echo "Tests that it works correctly with -l -p and no file names"
        echo "===== ./wordfreq -l -p"
        ./wordfreq -l -p <input | diff - testh.out | head
        echo "===== Stopping test h"
        ;;
     i) echo "Starting test i"
        echo "Tests that it works correctly with -lp and 1 file name"
        echo "===== ./wordfreq -lp input"
        ./wordfreq -lp input | diff - testi.out | head
        echo "===== Stopping test i"
        ;;
     j) echo "Starting test j"
        echo "Tests that it works correctly with -alp and a single file name"
        echo "===== ./wordfreq -alp input"
        ./wordfreq -alp input | diff - testj.out | head
        echo "===== Stopping test j"
        ;;
     k) echo "Starting test k"
        echo "Tests that it works correctly with -flp and a single file name"
        echo "===== ./wordfreq -flp input"
        ./wordfreq -flp input | diff - testk.out | head
        echo "===== Stopping test k"
        ;;
     l) echo "Starting test l"
        echo "Tests that it works correctly with -ailp and a single file name"
        echo "===== ./wordfreq -ailp input"
        ./wordfreq -ailp input | diff - testl.out | head
        echo "===== Stopping test l"
        ;;
     m) echo "Starting test m"
        echo "Tests that it works correctly with -filp and a single file name"
        echo "===== ./wordfreq -filp input"
        ./wordfreq -filp input | diff - testm.out | head
        echo "===== Stopping test m"
        ;;
     n) echo "Starting test n"
        echo "Tests that it works correctly with -alp and multiple files"
        echo "===== ./wordfreq -alp input input1 input2"
        ./wordfreq -alp input input1 input2 | diff - testn.out | head
        echo "===== Stopping test n"
        ;;
     o) echo "Starting test o"
        echo "Tests that it works correctly with -flp and multiple files"
        echo "===== ./wordfreq -flp input input1 input2"
        ./wordfreq -flp input input1 input2 | diff - testo.out | head
        echo "===== Stopping test o"
        ;;
     *) echo $t - illegal test
        ;;
    esac
done
